/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ServiceAreasRouteImport } from './routes/service-areas'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ReferralRouteImport } from './routes/referral'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as GivingBackRouteImport } from './routes/giving-back'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesWindowCleaningRouteImport } from './routes/services.window-cleaning'
import { Route as ServicesPropertyManagementCleaningRouteImport } from './routes/services.property-management-cleaning'
import { Route as ServicesPropertyCareRouteImport } from './routes/services.property-care'
import { Route as ServicesPressureWashingRouteImport } from './routes/services.pressure-washing'
import { Route as ServicesJanitorialInteriorCleaningRouteImport } from './routes/services.janitorial-interior-cleaning'
import { Route as ServicesAirbnbVrboTurnoverRouteImport } from './routes/services.airbnb-vrbo-turnover'
import { Route as ServiceAreasSlugRouteImport } from './routes/service-areas.$slug'
import { Route as IndustriesResidentialRouteImport } from './routes/industries.residential'
import { Route as IndustriesPropertyManagersRouteImport } from './routes/industries.property-managers'
import { Route as IndustriesDaycareRouteImport } from './routes/industries.daycare'
import { Route as IndustriesConstructionRouteImport } from './routes/industries.construction'
import { Route as IndustriesCommercialRouteImport } from './routes/industries.commercial'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreasRoute = ServiceAreasRouteImport.update({
  id: '/service-areas',
  path: '/service-areas',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralRoute = ReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const GivingBackRoute = GivingBackRouteImport.update({
  id: '/giving-back',
  path: '/giving-back',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesWindowCleaningRoute = ServicesWindowCleaningRouteImport.update({
  id: '/window-cleaning',
  path: '/window-cleaning',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesPropertyManagementCleaningRoute =
  ServicesPropertyManagementCleaningRouteImport.update({
    id: '/property-management-cleaning',
    path: '/property-management-cleaning',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesPropertyCareRoute = ServicesPropertyCareRouteImport.update({
  id: '/property-care',
  path: '/property-care',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesPressureWashingRoute = ServicesPressureWashingRouteImport.update({
  id: '/pressure-washing',
  path: '/pressure-washing',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesJanitorialInteriorCleaningRoute =
  ServicesJanitorialInteriorCleaningRouteImport.update({
    id: '/janitorial-interior-cleaning',
    path: '/janitorial-interior-cleaning',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesAirbnbVrboTurnoverRoute =
  ServicesAirbnbVrboTurnoverRouteImport.update({
    id: '/airbnb-vrbo-turnover',
    path: '/airbnb-vrbo-turnover',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServiceAreasSlugRoute = ServiceAreasSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServiceAreasRoute,
} as any)
const IndustriesResidentialRoute = IndustriesResidentialRouteImport.update({
  id: '/residential',
  path: '/residential',
  getParentRoute: () => IndustriesRoute,
} as any)
const IndustriesPropertyManagersRoute =
  IndustriesPropertyManagersRouteImport.update({
    id: '/property-managers',
    path: '/property-managers',
    getParentRoute: () => IndustriesRoute,
  } as any)
const IndustriesDaycareRoute = IndustriesDaycareRouteImport.update({
  id: '/daycare',
  path: '/daycare',
  getParentRoute: () => IndustriesRoute,
} as any)
const IndustriesConstructionRoute = IndustriesConstructionRouteImport.update({
  id: '/construction',
  path: '/construction',
  getParentRoute: () => IndustriesRoute,
} as any)
const IndustriesCommercialRoute = IndustriesCommercialRouteImport.update({
  id: '/commercial',
  path: '/commercial',
  getParentRoute: () => IndustriesRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/giving-back': typeof GivingBackRoute
  '/industries': typeof IndustriesRouteWithChildren
  '/partner': typeof PartnerRoute
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRoute
  '/referral': typeof ReferralRoute
  '/reviews': typeof ReviewsRoute
  '/service-areas': typeof ServiceAreasRouteWithChildren
  '/services': typeof ServicesRouteWithChildren
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/industries/commercial': typeof IndustriesCommercialRoute
  '/industries/construction': typeof IndustriesConstructionRoute
  '/industries/daycare': typeof IndustriesDaycareRoute
  '/industries/property-managers': typeof IndustriesPropertyManagersRoute
  '/industries/residential': typeof IndustriesResidentialRoute
  '/service-areas/$slug': typeof ServiceAreasSlugRoute
  '/services/airbnb-vrbo-turnover': typeof ServicesAirbnbVrboTurnoverRoute
  '/services/janitorial-interior-cleaning': typeof ServicesJanitorialInteriorCleaningRoute
  '/services/pressure-washing': typeof ServicesPressureWashingRoute
  '/services/property-care': typeof ServicesPropertyCareRoute
  '/services/property-management-cleaning': typeof ServicesPropertyManagementCleaningRoute
  '/services/window-cleaning': typeof ServicesWindowCleaningRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/giving-back': typeof GivingBackRoute
  '/industries': typeof IndustriesRouteWithChildren
  '/partner': typeof PartnerRoute
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRoute
  '/referral': typeof ReferralRoute
  '/reviews': typeof ReviewsRoute
  '/service-areas': typeof ServiceAreasRouteWithChildren
  '/services': typeof ServicesRouteWithChildren
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/industries/commercial': typeof IndustriesCommercialRoute
  '/industries/construction': typeof IndustriesConstructionRoute
  '/industries/daycare': typeof IndustriesDaycareRoute
  '/industries/property-managers': typeof IndustriesPropertyManagersRoute
  '/industries/residential': typeof IndustriesResidentialRoute
  '/service-areas/$slug': typeof ServiceAreasSlugRoute
  '/services/airbnb-vrbo-turnover': typeof ServicesAirbnbVrboTurnoverRoute
  '/services/janitorial-interior-cleaning': typeof ServicesJanitorialInteriorCleaningRoute
  '/services/pressure-washing': typeof ServicesPressureWashingRoute
  '/services/property-care': typeof ServicesPropertyCareRoute
  '/services/property-management-cleaning': typeof ServicesPropertyManagementCleaningRoute
  '/services/window-cleaning': typeof ServicesWindowCleaningRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/giving-back': typeof GivingBackRoute
  '/industries': typeof IndustriesRouteWithChildren
  '/partner': typeof PartnerRoute
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRoute
  '/referral': typeof ReferralRoute
  '/reviews': typeof ReviewsRoute
  '/service-areas': typeof ServiceAreasRouteWithChildren
  '/services': typeof ServicesRouteWithChildren
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/industries/commercial': typeof IndustriesCommercialRoute
  '/industries/construction': typeof IndustriesConstructionRoute
  '/industries/daycare': typeof IndustriesDaycareRoute
  '/industries/property-managers': typeof IndustriesPropertyManagersRoute
  '/industries/residential': typeof IndustriesResidentialRoute
  '/service-areas/$slug': typeof ServiceAreasSlugRoute
  '/services/airbnb-vrbo-turnover': typeof ServicesAirbnbVrboTurnoverRoute
  '/services/janitorial-interior-cleaning': typeof ServicesJanitorialInteriorCleaningRoute
  '/services/pressure-washing': typeof ServicesPressureWashingRoute
  '/services/property-care': typeof ServicesPropertyCareRoute
  '/services/property-management-cleaning': typeof ServicesPropertyManagementCleaningRoute
  '/services/window-cleaning': typeof ServicesWindowCleaningRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/faq'
    | '/giving-back'
    | '/industries'
    | '/partner'
    | '/privacy'
    | '/quote'
    | '/referral'
    | '/reviews'
    | '/service-areas'
    | '/services'
    | '/terms'
    | '/blog/$slug'
    | '/industries/commercial'
    | '/industries/construction'
    | '/industries/daycare'
    | '/industries/property-managers'
    | '/industries/residential'
    | '/service-areas/$slug'
    | '/services/airbnb-vrbo-turnover'
    | '/services/janitorial-interior-cleaning'
    | '/services/pressure-washing'
    | '/services/property-care'
    | '/services/property-management-cleaning'
    | '/services/window-cleaning'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/faq'
    | '/giving-back'
    | '/industries'
    | '/partner'
    | '/privacy'
    | '/quote'
    | '/referral'
    | '/reviews'
    | '/service-areas'
    | '/services'
    | '/terms'
    | '/blog/$slug'
    | '/industries/commercial'
    | '/industries/construction'
    | '/industries/daycare'
    | '/industries/property-managers'
    | '/industries/residential'
    | '/service-areas/$slug'
    | '/services/airbnb-vrbo-turnover'
    | '/services/janitorial-interior-cleaning'
    | '/services/pressure-washing'
    | '/services/property-care'
    | '/services/property-management-cleaning'
    | '/services/window-cleaning'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/faq'
    | '/giving-back'
    | '/industries'
    | '/partner'
    | '/privacy'
    | '/quote'
    | '/referral'
    | '/reviews'
    | '/service-areas'
    | '/services'
    | '/terms'
    | '/blog/$slug'
    | '/industries/commercial'
    | '/industries/construction'
    | '/industries/daycare'
    | '/industries/property-managers'
    | '/industries/residential'
    | '/service-areas/$slug'
    | '/services/airbnb-vrbo-turnover'
    | '/services/janitorial-interior-cleaning'
    | '/services/pressure-washing'
    | '/services/property-care'
    | '/services/property-management-cleaning'
    | '/services/window-cleaning'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  GivingBackRoute: typeof GivingBackRoute
  IndustriesRoute: typeof IndustriesRouteWithChildren
  PartnerRoute: typeof PartnerRoute
  PrivacyRoute: typeof PrivacyRoute
  QuoteRoute: typeof QuoteRoute
  ReferralRoute: typeof ReferralRoute
  ReviewsRoute: typeof ReviewsRoute
  ServiceAreasRoute: typeof ServiceAreasRouteWithChildren
  ServicesRoute: typeof ServicesRouteWithChildren
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas': {
      id: '/service-areas'
      path: '/service-areas'
      fullPath: '/service-areas'
      preLoaderRoute: typeof ServiceAreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referral': {
      id: '/referral'
      path: '/referral'
      fullPath: '/referral'
      preLoaderRoute: typeof ReferralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giving-back': {
      id: '/giving-back'
      path: '/giving-back'
      fullPath: '/giving-back'
      preLoaderRoute: typeof GivingBackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/window-cleaning': {
      id: '/services/window-cleaning'
      path: '/window-cleaning'
      fullPath: '/services/window-cleaning'
      preLoaderRoute: typeof ServicesWindowCleaningRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/property-management-cleaning': {
      id: '/services/property-management-cleaning'
      path: '/property-management-cleaning'
      fullPath: '/services/property-management-cleaning'
      preLoaderRoute: typeof ServicesPropertyManagementCleaningRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/property-care': {
      id: '/services/property-care'
      path: '/property-care'
      fullPath: '/services/property-care'
      preLoaderRoute: typeof ServicesPropertyCareRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/pressure-washing': {
      id: '/services/pressure-washing'
      path: '/pressure-washing'
      fullPath: '/services/pressure-washing'
      preLoaderRoute: typeof ServicesPressureWashingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/janitorial-interior-cleaning': {
      id: '/services/janitorial-interior-cleaning'
      path: '/janitorial-interior-cleaning'
      fullPath: '/services/janitorial-interior-cleaning'
      preLoaderRoute: typeof ServicesJanitorialInteriorCleaningRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/airbnb-vrbo-turnover': {
      id: '/services/airbnb-vrbo-turnover'
      path: '/airbnb-vrbo-turnover'
      fullPath: '/services/airbnb-vrbo-turnover'
      preLoaderRoute: typeof ServicesAirbnbVrboTurnoverRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/service-areas/$slug': {
      id: '/service-areas/$slug'
      path: '/$slug'
      fullPath: '/service-areas/$slug'
      preLoaderRoute: typeof ServiceAreasSlugRouteImport
      parentRoute: typeof ServiceAreasRoute
    }
    '/industries/residential': {
      id: '/industries/residential'
      path: '/residential'
      fullPath: '/industries/residential'
      preLoaderRoute: typeof IndustriesResidentialRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/industries/property-managers': {
      id: '/industries/property-managers'
      path: '/property-managers'
      fullPath: '/industries/property-managers'
      preLoaderRoute: typeof IndustriesPropertyManagersRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/industries/daycare': {
      id: '/industries/daycare'
      path: '/daycare'
      fullPath: '/industries/daycare'
      preLoaderRoute: typeof IndustriesDaycareRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/industries/construction': {
      id: '/industries/construction'
      path: '/construction'
      fullPath: '/industries/construction'
      preLoaderRoute: typeof IndustriesConstructionRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/industries/commercial': {
      id: '/industries/commercial'
      path: '/commercial'
      fullPath: '/industries/commercial'
      preLoaderRoute: typeof IndustriesCommercialRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface IndustriesRouteChildren {
  IndustriesCommercialRoute: typeof IndustriesCommercialRoute
  IndustriesConstructionRoute: typeof IndustriesConstructionRoute
  IndustriesDaycareRoute: typeof IndustriesDaycareRoute
  IndustriesPropertyManagersRoute: typeof IndustriesPropertyManagersRoute
  IndustriesResidentialRoute: typeof IndustriesResidentialRoute
}

const IndustriesRouteChildren: IndustriesRouteChildren = {
  IndustriesCommercialRoute: IndustriesCommercialRoute,
  IndustriesConstructionRoute: IndustriesConstructionRoute,
  IndustriesDaycareRoute: IndustriesDaycareRoute,
  IndustriesPropertyManagersRoute: IndustriesPropertyManagersRoute,
  IndustriesResidentialRoute: IndustriesResidentialRoute,
}

const IndustriesRouteWithChildren = IndustriesRoute._addFileChildren(
  IndustriesRouteChildren,
)

interface ServiceAreasRouteChildren {
  ServiceAreasSlugRoute: typeof ServiceAreasSlugRoute
}

const ServiceAreasRouteChildren: ServiceAreasRouteChildren = {
  ServiceAreasSlugRoute: ServiceAreasSlugRoute,
}

const ServiceAreasRouteWithChildren = ServiceAreasRoute._addFileChildren(
  ServiceAreasRouteChildren,
)

interface ServicesRouteChildren {
  ServicesAirbnbVrboTurnoverRoute: typeof ServicesAirbnbVrboTurnoverRoute
  ServicesJanitorialInteriorCleaningRoute: typeof ServicesJanitorialInteriorCleaningRoute
  ServicesPressureWashingRoute: typeof ServicesPressureWashingRoute
  ServicesPropertyCareRoute: typeof ServicesPropertyCareRoute
  ServicesPropertyManagementCleaningRoute: typeof ServicesPropertyManagementCleaningRoute
  ServicesWindowCleaningRoute: typeof ServicesWindowCleaningRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesAirbnbVrboTurnoverRoute: ServicesAirbnbVrboTurnoverRoute,
  ServicesJanitorialInteriorCleaningRoute:
    ServicesJanitorialInteriorCleaningRoute,
  ServicesPressureWashingRoute: ServicesPressureWashingRoute,
  ServicesPropertyCareRoute: ServicesPropertyCareRoute,
  ServicesPropertyManagementCleaningRoute:
    ServicesPropertyManagementCleaningRoute,
  ServicesWindowCleaningRoute: ServicesWindowCleaningRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  GivingBackRoute: GivingBackRoute,
  IndustriesRoute: IndustriesRouteWithChildren,
  PartnerRoute: PartnerRoute,
  PrivacyRoute: PrivacyRoute,
  QuoteRoute: QuoteRoute,
  ReferralRoute: ReferralRoute,
  ReviewsRoute: ReviewsRoute,
  ServiceAreasRoute: ServiceAreasRouteWithChildren,
  ServicesRoute: ServicesRouteWithChildren,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
